[theme]
primaryColor = "#0d6efd"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1a1c2e"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
